AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'vendor/bundle/**/*'
    - 'rds_postgresql_slowquery_to_es/vendor/**/*'
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
