@startditaa
+-----+    +----------+    +--------------------------------+    +-------------+
|     |    |          |    |               SAM              |    |             |
| RDS |    |CloudWatch|    | rds_postgresql_slowquery_to_es |    |Elasticsearch|
|  {s}+--->|   Logs   +--->|                                +--->|   Service   |
|     |    |       {d}|    |      (Subscription Filter)     |    |          {s}|
+-----+    +----------+    +--------------------------------+    +-------------+
@endditaa
